name: PHP Composer

on:
  push:
    branches: [ main ]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Setup PHP with pre-release PECL extension
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'
    - uses: actions/checkout@v2
    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress
    
    - name: Bump Version
      uses: remorses/bump-version@v8
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        tag_version: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test
